### ISSUE TITLE
Bug: buffers are not added to the buffer list when reopened

### ISSUE THREAD

**Issue by mroavi** [yegappan/mru#45]
The first time a buffer is opened with MRU, it is added to the buffer list. If, however, the buffer is deleted and reopened at a later point again with MRU, it does not get added to the buffer list. I find this behavior buggy. Let me know if you agree.

Here is a gif that illustrates the above:

![Peek 2021-08-03 00-54_mru_buffer_list_bug](https://user-images.githubusercontent.com/19517248/127934351-f7523b45-3352-4d5f-8940-90e4dd8de997.gif)

I am running NVIM v0.5.0.

**Comment by yegappan** [comment]
Thanks for reporting the issue.
I have pushed PR cf9b8ba6944522ff1b8eaa1ef7582830e1711432 fix this issue.
Let me know, if you see any other problem with this.

**Comment by mroavi** [comment]
I pulled your change. The issue doesn't seem to be solved. I still see the same behavior as shown in the GIF above.

**Comment by yegappan** [comment]
With the latest version of the plugin, I am not able to reproduce the problem
using the steps shown in the GIF. Can you check the mru.vim plugin file to
make sure the changes are present?

**Comment by mroavi** [comment]
I verified that the changes are present:
```
commit cf9b8ba6944522ff1b8eaa1ef7582830e1711432
  Author: Yegappan Lakshmanan <yegappan@yahoo.com>
  Date:   10 hours ago
```
